# Introduction to Numpy Problem Set

Problem 1

In [2]:
import numpy as np

In [10]:
def prob1():
    A = np.array([[3,-1,4], [1,5,-9]])
    B = np.array([[2,6,-5,3], [5,-8,9,7], [9,-3,-2,-3]])
    return A@B

prob1()
    

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2

In [14]:
def prob2():
    A = np.array([[3,1,4], [1,5,9], [-5,3,1]])
    A3 = (A@A)@A
    A2 = A@A
    return -A3 + 9*A2 - 15*A

prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3


In [18]:
def prob3():
    A = np.ones((7,7))
    A = np.triu(A)
    B = np.ones((7,7))
    C = np.tril(B)*-1
    D = np.triu(B)*5
    B = C + D
    I = np.eye(7,7)*5
    B = B - I
    mult = A@B@A
    mult = mult.astype(np.int64)
    return mult

prob3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4

In [19]:
def prob4(A):
    B = np.copy(A)
    mask = B < 0
    B[mask] = 0
    return B

Problem 5

In [21]:
def prob5():
    A = np.array([[0,2,4], [1,3,5]])
    B = np.array([[3,0,0], [3,3,0], [3,3,3]])
    C = np.array([[-2,0,0], [0,-2,0], [0,0,-2]])
    O1 = np.zeros((3,3))
    O21 = np.zeros((2,2))
    O22 = np.zeros((2,3))
    O3 = np.zeros((3,2))
    I = np.eye(3,3)
    R1 = np.hstack((O1, A.T, I))
    R2 = np.hstack((A, O21, O22))
    R3 = np.hstack((B, O3, C))
    matrix = np.vstack((R1,R2,R3))
    return matrix
prob5()
    

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

Problem 6

In [3]:
def prob6(A):
    rowsum = np.sum(A, axis=1).reshape(-1,1)
    A = A / rowsum
    return A
prob6(np.array([[1,1,1], [2,2,2], [3,3,3], [4,4,4]]))

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [3]:
def prob7():
    grid = np.load("grid.npy")
    rowmax = np.max(grid[:, :-3] * grid[:, 1:-2] * grid[:, 2:-1] * grid[:, 3:])
    colmax = np.max(grid[:-3, :] * grid[1:-2, :] * grid[2:-1] * grid[3:, :])
    lowdiagmax = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    updiagmax = np.max(grid[3:, :-3] * grid[2:-1, 1:-2] * grid[1:-2, 2:-1] * grid[:-3, 3:])
    return np.max([rowmax, colmax, lowdiagmax, updiagmax])
prob7()

70600674

# Standard Library Problem Set

Problem 1

In [4]:
def prob1(L):
    R = [min(L), max(L), sum(L)/len(L)]
    return R
prob1([1,2,3,4,5])

[1, 5, 3.0]

Problem 2

In [10]:
'''Integer'''
Integer_1 = 5
Integer_2 = Integer_1
Integer_2 += 1
print(Integer_1 == Integer_2)


'''String'''
String_1 = 'keshav'
String_2 = String_1
String_2 += 'choudhary'
print(String_1 == String_2)


'''List'''
List_1 = [1,2,3]
List_2 = List_1
List_2[2] += 1  
print(List_1 == List_2)


'''Tuple'''
tuple1 = (1,2,3)
tuple2 = tuple1
tuple2 += (1,3)
print(tuple1 == tuple2)


'''Set'''
set1 = {1, 2, 3, 4}
set2 = set1
set2.add('a')
print(set1 == set2)


False
False
True
False
True


Problem 3

In [7]:
import calculator as calc
def hypotenuse(a,b):
    C = calc.sqrt(calc.sum(calc.product(a,a), calc.product(b,b)))
    return C
hypotenuse(3,4)

5.0

Problem 4

In [3]:
from itertools import combinations, chain

def power(A):
    B = []
    for i in range (len(A)+1):
        B.append(list(combinations(A, i)))
    C = list(chain(*B)) 
    D = []
    for i in range(len(C)):
        D.append(set(C[i]))    
    return D

power({1,2,3})

[[()], [(1,), (2,), (3,)], [(1, 2), (1, 3), (2, 3)], [(1, 2, 3)]]


[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]

# Unit Testing Problem Set

Problem 1

There is a file called prob1.py in the folder. This contains the original program. The file test_prob1.py in the same folder contains the test, which checks for perfect squares. The test fails for perfect squares. The corrected function is:

In [1]:
def smallest_factor(n):
    if n==1: return 1
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return i
    return n



Problem 2