# Introduction to Numpy Problem Set

Problem 1

In [2]:
import numpy as np

In [10]:
def prob1():
    A = np.array([[3,-1,4], [1,5,-9]])
    B = np.array([[2,6,-5,3], [5,-8,9,7], [9,-3,-2,-3]])
    return A@B

prob1()
    

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2

In [14]:
def prob2():
    A = np.array([[3,1,4], [1,5,9], [-5,3,1]])
    A3 = (A@A)@A
    A2 = A@A
    return -A3 + 9*A2 - 15*A

prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3


In [18]:
def prob3():
    A = np.ones((7,7))
    A = np.triu(A)
    B = np.ones((7,7))
    C = np.tril(B)*-1
    D = np.triu(B)*5
    B = C + D
    I = np.eye(7,7)*5
    B = B - I
    mult = A@B@A
    mult = mult.astype(np.int64)
    return mult

prob3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4

In [19]:
def prob4(A):
    B = np.copy(A)
    mask = B < 0
    B[mask] = 0
    return B

Problem 5

In [21]:
def prob5():
    A = np.array([[0,2,4], [1,3,5]])
    B = np.array([[3,0,0], [3,3,0], [3,3,3]])
    C = np.array([[-2,0,0], [0,-2,0], [0,0,-2]])
    O1 = np.zeros((3,3))
    O21 = np.zeros((2,2))
    O22 = np.zeros((2,3))
    O3 = np.zeros((3,2))
    I = np.eye(3,3)
    R1 = np.hstack((O1, A.T, I))
    R2 = np.hstack((A, O21, O22))
    R3 = np.hstack((B, O3, C))
    matrix = np.vstack((R1,R2,R3))
    return matrix
prob5()
    

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

Problem 6

In [3]:
def prob6(A):
    rowsum = np.sum(A, axis=1).reshape(-1,1)
    A = A / rowsum
    return A
prob6(np.array([[1,1,1], [2,2,2], [3,3,3], [4,4,4]]))

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [3]:
def prob7():
    grid = np.load("grid.npy")
    rowmax = np.max(grid[:, :-3] * grid[:, 1:-2] * grid[:, 2:-1] * grid[:, 3:])
    colmax = np.max(grid[:-3, :] * grid[1:-2, :] * grid[2:-1] * grid[3:, :])
    lowdiagmax = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    updiagmax = np.max(grid[3:, :-3] * grid[2:-1, 1:-2] * grid[1:-2, 2:-1] * grid[:-3, 3:])
    return np.max([rowmax, colmax, lowdiagmax, updiagmax])
prob7()

70600674

# Standard Library Problem Set

Problem 1

In [4]:
def prob1(L):
    R = [min(L), max(L), sum(L)/len(L)]
    return R
prob1([1,2,3,4,5])

[1, 5, 3.0]

Problem 2

In [10]:
'''Integer'''
Integer_1 = 5
Integer_2 = Integer_1
Integer_2 += 1
print(Integer_1 == Integer_2)


'''String'''
String_1 = 'keshav'
String_2 = String_1
String_2 += 'choudhary'
print(String_1 == String_2)


'''List'''
List_1 = [1,2,3]
List_2 = List_1
List_2[2] += 1  
print(List_1 == List_2)


'''Tuple'''
tuple1 = (1,2,3)
tuple2 = tuple1
tuple2 += (1,3)
print(tuple1 == tuple2)


'''Set'''
set1 = {1, 2, 3, 4}
set2 = set1
set2.add('a')
print(set1 == set2)


False
False
True
False
True


Problem 3

In [7]:
import calculator as calc
def hypotenuse(a,b):
    C = calc.sqrt(calc.sum(calc.product(a,a), calc.product(b,b)))
    return C
hypotenuse(3,4)

5.0

Problem 4

In [3]:
from itertools import combinations, chain

def power(A):
    B = []
    for i in range (len(A)+1):
        B.append(list(combinations(A, i)))
    C = list(chain(*B)) 
    D = []
    for i in range(len(C)):
        D.append(set(C[i]))    
    return D

power({1,2,3})

[[()], [(1,), (2,), (3,)], [(1, 2), (1, 3), (2, 3)], [(1, 2, 3)]]


[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]

Problem 5

See shut_the_box.py

# Unit Testing Problem Set

Problem 1

There is a file called prob1.py in the folder. This contains the original program. The file test_prob1.py in the same folder contains the test, which checks for perfect squares. The test fails for perfect squares. The corrected function is:

In [1]:
def smallest_factor(n):
    if n==1: return 1
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return i
    return n



Also See prob1.py and test_prob1.py

Problem 2

The unit test for Problem 1 in the file test_prob1.py is-


In [1]:
import prob1

def test_prob1():
    assert prob1.smallest_factor(25) == 5, "Failed on perfect squares"


This has 100% coverage.

The comprehensive unit test for the function returning the number of months is- 

In [3]:
import prob2

def test_prob2():
    assert prob2.month_length("January", False) == 31, "Error in January in non-leap year"
    assert prob2.month_length("February", False) == 28, "Error in February in non-leap year"
    assert prob2.month_length("March", False) == 31, "Error in March in non-leap year"
    assert prob2.month_length("April", False) == 30, "Error in April in non-leap year"
    assert prob2.month_length("May", False) == 31, "Error in May in non-leap year"
    assert prob2.month_length("June", False) == 30, "Error in June in non-leap year"
    assert prob2.month_length("July", False) == 31, "Error in July in non-leap year"
    assert prob2.month_length("August", False) == 31, "Error in August in non-leap year"
    assert prob2.month_length("September", False) == 30, "Error in September in non-leap year"
    assert prob2.month_length("October", False) == 31, "Error in October in non-leap year"
    assert prob2.month_length("November", False) == 30, "Error in Novemberin non-leap year"
    assert prob2.month_length("December", False) == 31, "Error in December in non-leap year"
    assert prob2.month_length("February", True) == 29, "Error in February in leap year"
    assert prob2.month_length("XYZ", True) == None, "Error when no month is inputted"


This test achieves 100% coverage. 
Also see prob2.py and test_prob2.py 


Problem 3

The code for the unit test is- 

In [4]:
import prob3
import pytest

def test_operate():
    with pytest.raises(TypeError) as excinfo1:
        prob3.operate(1,2,1)
    assert excinfo1.value.args[0] == "oper must be a string"
    assert prob3.operate(1,2,'+') == 3, "addition error"
    assert prob3.operate(4,1, '-') == 3 , "subtraction error"
    assert prob3.operate(3,2,'*') == 6, 'multiplication error'
    assert prob3.operate(8,2,'/') == 4, 'division error'
    with pytest.raises(ZeroDivisionError) as excinfo2:
        prob3.operate(1,0,'/')
    assert excinfo2.value.args[0] == "division by zero is undefined"
    with pytest.raises(ValueError) as excinfo3:
        prob3.operate(1,3,'(')
    assert excinfo3.value.args[0] == "oper must be one of '+', '/', '-', or '*'"


This test achieves 100% coverage. Also see prob3.py and test_prob3.py

Problem 4

The code for the Unit Test is-

In [1]:
import prob4
import pytest

@pytest.fixture
def set_up_fractions():
    frac_1_3 = prob4.Fraction(1, 3)
    frac_1_2 = prob4.Fraction(1, 2)
    frac_n2_3 = prob4.Fraction(-2, 3)
    frac_5_1 = prob4.Fraction(5,1)
    frac_5_6 = prob4.Fraction(5,6)
    return frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6


def test_fraction_init(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6 = set_up_fractions
    assert frac_1_3.numer == 1
    assert frac_1_2.denom == 2
    assert frac_n2_3.numer == -2
    frac = prob4.Fraction(30, 42)
    assert frac.numer == 5
    assert frac.denom == 7

    with pytest.raises(ZeroDivisionError) as excinfo1:
        prob4.Fraction(5,0)
    assert excinfo1.value.args[0] == "denominator cannot be zero"

    with pytest.raises(TypeError) as excinfo2:
        prob4.Fraction(1.3, 4.2)
    assert excinfo2.value.args[0] == "numerator and denominator must be integers"


def test_fraction_str(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6 = set_up_fractions
    assert str(frac_1_3) == "1/3"
    assert str(frac_1_2) == "1/2"
    assert str(frac_n2_3) == "-2/3"
    assert str(frac_5_1) == "5"


def test_fraction_float(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6 = set_up_fractions
    assert float(frac_1_3) == 1 / 3.
    assert float(frac_1_2) == .5
    assert float(frac_n2_3) == -2 / 3.


def test_fraction_eq(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6 = set_up_fractions
    assert frac_1_2 == prob4.Fraction(1, 2)
    assert frac_1_3 == prob4.Fraction(2, 6)
    assert frac_n2_3 == prob4.Fraction(8, -12)

    assert float(frac_1_2) == frac_1_2

def test_fraction_add(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6 = set_up_fractions
    assert frac_1_2 + frac_1_3 == frac_5_6

def test_fraction_sub(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6  = set_up_fractions
    assert frac_5_6 - frac_1_2 == frac_1_3

def test_fraction_mul(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6  = set_up_fractions
    assert frac_1_3 * frac_1_2 == prob4.Fraction(1,6)

def test_fraction_truediv(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3, frac_5_1, frac_5_6  = set_up_fractions
    assert frac_1_3 / frac_1_2 == prob4.Fraction(2,3)

    with pytest.raises(ZeroDivisionError) as excinfo3:
        frac_5_1 / prob4.Fraction(0,5)
    assert excinfo3


This test achieves 100% coverage. There is error in the addition and subtraction operations which has been corrected. Also see prob4.py and test_prob4.py

See prob5.py and test_prob5.py

# Object Oriented Programming Problem Set

Problem 1

The code for the backpack class is 

In [1]:
class Backpack:
    '''A backpack object class. Has name and color'''

    def __init__(self, name, color, max_size=5):

        '''Set the name and color and initiate an empty list of contents'''
        '''Parameters- name (string), color(string)'''
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):

        '''Append items till backpack items are lesser than maximum size'''

        if len(self.contents) < self.max_size:
            return self.contents.append(item)
        else: print("No more room!")

    def dump(self):
        '''wipe out all contents of backpack'''
        self.contents = []


To test the backpack class, we can write the following function-

In [2]:
def test_backpack():
    testpack = Backpack("Barry", "black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer", "earphones", "charger"]:
        testpack.put(item)
    print("contents: ", testpack.contents)
    testpack.dump()
    print("contents after dump: ", testpack.contents)

test_backpack()


No more room!
contents:  ['pencil', 'pen', 'paper', 'computer', 'earphones']
contents after dump:  []


Problem 2

In [3]:
class Jetpack(Backpack):
    def __init__(self, name, color, max_size =2, fuel=10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
        self.maxsize= max_size
    
    def fly(self, fuel):
        if self.fuel >= fuel:
            self.fuel = self.fuel - fuel
        else: print("Not enough fuel!")
            
    def dump(self):
        self.contents = []
        self.fuel = 0
    

In [4]:
def test_Jetpack():
    my_jetpack = Jetpack("Keshav", "Black")
    for item in ["pencil", "pen", "charger"]:
        my_jetpack.put(item)
    my_jetpack.fly(7)
    print("Jetpack contents: ", my_jetpack.contents)
    print("Fuel remaining: ", my_jetpack.fuel)
    my_jetpack.dump()
    print("Contents and fuel after dump: ", my_jetpack.contents, my_jetpack.fuel)
    
test_Jetpack()

No more room!
Jetpack contents:  ['pencil', 'pen']
Fuel remaining:  3
Contents and fuel after dump:  [] 0


Problem 3

In [5]:
class Backpack:
    '''A backpack object class. Has name and color'''

    def __init__(self, name, color, max_size=5):

        '''Set the name and color and initiate an empty list of contents'''
        '''Parameters- name (string), color(string)'''
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):

        '''Append items till backpack items are lesser than maximum size'''

        if len(self.contents) < self.max_size:
            return self.contents.append(item)
        else: print("No more room!")

    def dump(self):
        '''wipe out all contents of backpack'''
        self.contents = []
        
    def __eq__(self, other):
        return (self.name == other.name) and (len(self.contents) == len(other.contents)) and (self.color == other.color)
    
    def __str__(self):
        dstring = ('Owner:\t \t' + str(self.name) + '\nColor: \t \t' + str(self.color) + '\nSize: \t \t' +  str(len(self.contents))
                   + '\nMax Size:\t' + str(self.max_size) + '\nContents: \t' + str(self.contents))
        return dstring

In [6]:
pack1 = Backpack("Mary", "Magenta")
pack1.put("pens")
print(pack1)

Owner:	 	Mary
Color: 	 	Magenta
Size: 	 	1
Max Size:	5
Contents: 	['pens']


Problem 4

In [193]:
class ComplexNumber:
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
    
    def conjugate(self):
        return ComplexNumber(self.real, -self.imag)
    
    def __str__(self):
        if self.imag >= 0:
            dstring = "("+str(self.real) + "+" + str(self.imag)+ "j)"
        else: dstring = str(self.real) + "-" + str(abs(self.imag)) + "j"
        return dstring
    
    def __abs__(self):
        return ((self.real**2)+ (self.imag**2))**0.5
    
    def __eq__(self, other):
        return (self.real==other.real) and (self.imag==other.imag)
    
    def __add__(self, other):
        a = self.real + other.real
        b = self.imag + other.imag
        return ComplexNumber(a,b)
    
    def __sub__(self, other):
        a = self.real - other.real
        b = self.imag - other.imag
        return ComplexNumber(a,b)
    
    def __mul__(self, other):
        a = self.real * other.real - self.imag * other.imag
        b = self.real *  other.imag + other.real * self.imag
        return ComplexNumber(a,b)
    
    def __truediv__(self, other):
        if other.real == 0 and other.imag ==0:
            return "division by 0 not allowed"
        else:
            z= other.real**2 + other.imag**2
            a = self.real * other.real + self.imag * other.imag
            b = self.imag * other.real - self.real * other.imag
            return ComplexNumber(a/z,b/z)
    
    
        
        
        
        
    
    

In [194]:
def test_ComplexNumber(a, b):
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print(py_cnum)
        print(my_cnum)
        print("__str__() failed for", py_cnum)
        
    test = ComplexNumber(5, 7)
    print(test + my_cnum)
    print(test * my_cnum)
    print(test / my_cnum)
        
test_ComplexNumber(1, 2)

(6+9j)
(-9+17j)
3.8-0.6j


# Exceptions and File Input/Output

Problem 1

In [195]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                       "digits differ by 2 or more: ")
    try:
        value = int(step_1)
    except ValueError:
        print("You did not enter an integer.")
        
    if len(step_1) != 3:
        raise ValueError("You did not enter a 3-digit integer.")
    
    if abs(int(step_1[0]) - int(step_1[2])) < 2:
        raise ValueError("The first number's first and last digits differ by less than 2") 
          
    step_2 = input("Enter the reverse of the first number, obtained "
                                          "by reading it backwards: ")
    
    reverseString = step_1[::-1]
    if step_2 != reverseString:
        raise ValueError("You did not reverse the first number.")
        
    step_3 = input("Enter the positive difference of these numbers: ")
    
    try:
        value = int(step_3)
    except ValueError:
        print("You did not enter an integer.")
        
    posDiff = abs(int(step_1) - int(reverseString))
    if int(step_3) != posDiff:
        raise ValueError("You did not enter the positive difference of these numbers")
        
    step_4 = input("Enter the reverse of the previous result: ")
    
    reverseString2 = step_3[::-1]
    if step_4 != reverseString2:
        raise ValueError("You did not reverse the third number.")

    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")
    
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 123
Enter the reverse of the first number, obtained by reading it backwards: 321
Enter the positive difference of these numbers: 198
Enter the reverse of the previous result: 891
198 + 891 = 1089 (ta-da!)


Problem 2

In [ ]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    
    try:
        for ind, ii in enumerate(range(int(max_iters))):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Process interrupted at iteration", ind)
    else:
        print("Process completed.")
    finally:   
        print("Value of the walk was: ", walk)
        return walk

random_walk()