In [1]:
import numpy as np


In [11]:
def prob6(A):
    rowsum = np.sum(A, axis=1).reshape(-1,1)
    A = A / rowsum
    return A
prob6(np.array([[1,2,3], [4,5,6], [8,9,10], [11,12,13]]))

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ],
       [0.2962963 , 0.33333333, 0.37037037],
       [0.30555556, 0.33333333, 0.36111111]])

In [12]:
grid = load("grid.npy")

NameError: name 'load' is not defined

In [13]:
grid = np.load("grid.npy")

In [17]:
A = np.array([[1,2,3,4,5,6], [4,5,6,7,8,9], [7,8,9,10,11,12]])

In [18]:
A


array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
B = A[:, 1:]

In [20]:
B

array([[ 2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12]])

In [21]:
C = A[:, 2:]

In [22]:
C

array([[ 3,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 9, 10, 11, 12]])

In [23]:
D = A[:, 3:]

In [24]:
D

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
A*B*C*D

ValueError: operands could not be broadcast together with shapes (3,6) (3,5) 

In [27]:
A = np.array([[1,2,3], [4,5,6]])

In [28]:
A[:,:-1]

array([[1, 2],
       [4, 5]])

In [29]:
A[:, :-2]

array([[1],
       [4]])

In [30]:
grid = np.load("grid.npy")

In [31]:
A = grid[:, :-3]
B = grid[:, 1:-2]
C = grid[:, 2:-1]
D = grid[:, 3:]
E = np.max(A*B*C*D)

In [32]:
E

48477312

In [35]:
A = grid[:-3, :]
B = grid[1:-2, :]
C = grid[2:-1, :]
D = grid[3:, :]
E = np.max(A*B*C*D)

In [36]:
E

51267216

In [43]:
A = np.arange(0,9).reshape((3,-1))

In [44]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
B = np.diag(A)

In [46]:
B

array([0, 4, 8])

In [47]:
A = np.diag(grid)

In [48]:
A

array([ 8, 49, 31, 23, 51,  3, 67, 20, 97, 45,  3, 24, 44, 52, 26, 32, 40,
        4,  5, 48])

In [49]:
A = np.arange(0,9).reshape((3,-1))

In [50]:
A = np.diag(grid)[:-3]
B = np.diag(grid)[1:-2]
C = np.diag(grid)[2:-1]
D = np.diag(grid)[3:]

In [51]:
E = np.max(A*B*C*D)

In [59]:
A = np.diag(grid[:, 1:])[:-3]
B = np.diag(grid[:, 1:])[1:-2]
C = np.diag(grid[:, 1:])[2:-1]
D = np.diag(grid[:, 1:])[3:]

In [60]:
E = np.max(A*B*C*D)

In [61]:
E

11108664

In [63]:
lowdiag = np.max(np.diag(grid[:, 1:])[:-3] * np.diag(grid[:, 1:])[1:-2] * np.diag(grid[:, 1:])[2:-1] *  np.diag(grid[:, 1:])[3:]) 

In [64]:
lowdiag

11108664

In [65]:
for i in range(5):
    print(i)

0
1
2
3
4


In [66]:
np.append(0)

TypeError: append() missing 1 required positional argument: 'values'

In [67]:
A = ([1,2,3])

In [68]:
A


[1, 2, 3]

In [71]:
A = np.array([1,2,3])

In [77]:
ld = np.array([0])
for i in range(17):
    A = np.max(np.diag(grid[:, i:])[:-3] * np.diag(grid[:, i:])[1:-2] * 
                     np.diag(grid[:, i:])[2:-1] *  np.diag(grid[:, i:])[3:])
    ld = np.append(ld, A)

lowdiag = ld[1:]


In [78]:
lowdiag


array([ 5849100, 11108664, 17959788, 13987952, 30692718, 14035428,
        4580064, 20335536,  7796880, 32565456,  5278770, 13522432,
        6044940,  1025640,   244608,   149760,  9172800])

In [79]:
ld1 = np.array([0])
for i in range(17):
    A = np.max(np.diag(grid[:, i:])[:-3] * np.diag(grid[:, i:])[1:-2] *
                     np.diag(grid[:, i:])[2:-1] *  np.diag(grid[:, i:])[3:])
    ld1 = np.append(ld1, A)

lowdiag1 = ld1[1:]

ld2 = np.array([0])
for i in range (17):
    A = np.max(np.diag(grid[i:, :])[:-3] * np.diag(grid[i:, :])[1:-2] *
                     np.diag(grid[i:, :])[2:-1] *  np.diag(grid[i:, :])[3:])
    ld2 = np.append(ld2, A)
lowdiag2 = ld2[1:]

lowdiag = np.append(lowdiag1, lowdiag2)
diagmax = np.max(lowdiag)


In [80]:
diagmax


40304286

In [81]:
lowdiag2


array([ 5849100, 32719995, 23569920, 20444380, 17085816,  6600672,
       10969344, 40304286, 23451120,   382602, 23365056, 21459816,
        8926200, 18585216,  2609568,  3858624,   685860])

In [82]:
lowdiag1

array([ 5849100, 11108664, 17959788, 13987952, 30692718, 14035428,
        4580064, 20335536,  7796880, 32565456,  5278770, 13522432,
        6044940,  1025640,   244608,   149760,  9172800])

In [83]:
lowdiagmax = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:]) 

In [84]:
lowdiagmax

40304286

In [86]:
A = np.array([1,2,3,4,5,6])

In [87]:
A[-1:]

array([6])

In [88]:
A[-2:]

array([5, 6])

In [89]:
A[2:]

array([3, 4, 5, 6])

In [90]:
A[1:]

array([2, 3, 4, 5, 6])

In [91]:
updiagmax = np.max(grid[3:, :-3] * grid[2:-1, 1:-2] * grid[1:-2, 2:-1] * grid[:-3, 3:])

In [92]:
updiagmax

70600674

In [5]:
A = [1,2,3]
type(A)

list

In [7]:
def prob1(L):
    R = [min(L), max(L), sum(L)/len(L)]
    return R
prob1([10,11,12,15,120])    

[10, 120, 33.6]

In [8]:
beatles = ['John', 'Paul', 'George', 'Ringo']
print(beatles)

['John', 'Paul', 'George', 'Ringo']


In [9]:
dict_1 = {1:'x', 2:'b'}
dict_1[2]

'b'

In [10]:
A = 1


In [11]:
A

1

In [12]:
type(A)

int

In [37]:
'''Integer'''
Integer_1 = 5
Integer_2 = Integer_1
Integer_2 += 1
print(Integer_1 == Integer_2)


'''String'''
String_1 = 'keshav'
String_2 = String_1
String_2 += 'choudhary'
print(String_1 == String_2)


'''List'''
List_1 = [1,2,3]
List_2 = List_1
List_2[2] += 1  
print(List_1 == List_2)


'''Tuple'''
tuple1 = (1,2,3)
tuple2 = tuple1
tuple2 += (1,3)
print(tuple1 == tuple2)


'''Set'''
set1 = {'elem1': 1, 'elem2': 2, 'elem3': 3, 'elem4': 4}
set2 = set1
set2['elem1'] = 'a'
print(set1 == set2)



False
False
True
False
True


In [38]:
import calculator.py


ModuleNotFoundError: No module named 'calculator.py'; 'calculator' is not a package

In [39]:
import calculator.py as calc

ModuleNotFoundError: No module named 'calculator.py'; 'calculator' is not a package

In [55]:
import calculator as calc

In [57]:
def hypotenuse(a,b):
    C = calc.sqrt(calc.sum(calc.product(a,a), calc.product(b,b)))
    return C
hypotenuse(3,4)


5.0

In [11]:
import numpy as np
A = np.array([])
A
    

array([], dtype=float64)

In [214]:
from itertools import combinations
list(combinations({1,2,3},1))

[(1,), (2,), (3,)]

In [9]:
from itertools import combinations, chain

def power(A):
    B = []
    for i in range (len(A)+1):
        B.append(list(combinations(A, i)))
    C = list(chain(*B)) 
    D = []
    for i in range(len(C)):
        D.append(set(C[i]))    
    return D



power({1,2,5,5,6,7})

    

    

    


[set(),
 {1},
 {2},
 {5},
 {6},
 {7},
 {1, 2},
 {1, 5},
 {1, 6},
 {1, 7},
 {2, 5},
 {2, 6},
 {2, 7},
 {5, 6},
 {5, 7},
 {6, 7},
 {1, 2, 5},
 {1, 2, 6},
 {1, 2, 7},
 {1, 5, 6},
 {1, 5, 7},
 {1, 6, 7},
 {2, 5, 6},
 {2, 5, 7},
 {2, 6, 7},
 {5, 6, 7},
 {1, 2, 5, 6},
 {1, 2, 5, 7},
 {1, 2, 6, 7},
 {1, 5, 6, 7},
 {2, 5, 6, 7},
 {1, 2, 5, 6, 7}]

In [ ]:
import numpy as np
from itertools import combinations, chain

def power(A):
    B = np.array([])
    for i in range (len(A)+1):
        np.append(combinations(A, i))
    print(B)
    C = list(chain(*B)) 
    D = []
    for i in range(len(C)):
        D.append(set(C[i]))    
    return D

power({1,2,3})